//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoBoticatio
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepositoriesLanguages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RepositoriesLanguages()
        {
            this.RepositoriesItemsDetails = new HashSet<RepositoriesItemsDetails>();
        }
    
        public string Language { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepositoriesItemsDetails> RepositoriesItemsDetails { get; set; }
    }
}
