//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoBoticatio
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepositoriesItemsDetails
    {
        public int Id { get; set; }
        public string RepositoryId { get; set; }
        public string Language { get; set; }
        public string FullName { get; set; }
        public string HtmlUrl { get; set; }
        public string Description { get; set; }
        public short IsPrivate { get; set; }
        public int StargazersCount { get; set; }
        public int Page { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual RepositoriesLanguages RepositoriesLanguages { get; set; }
    }
}
